apiVersion: v1
kind: Service
metadata:
  name: skaffold-spring-boot
  labels:
    name: skaffold-spring-boot
spec:
  selector:
    app: skaffold-spring-boot
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000